# Site settings
title: ForEvolve
subtitle: A piece of mind...
header-img: //cdn.forevolve.com/blog/images/pages-header/default-header.jpg
override-header-img-with-post-img: false
copyright_name: Carl-Hugo Marcotte
description: 'A piece of mind'
baseurl: ''
url: 'http://www.forevolve.com'
remoteUrl: 'https://www.forevolve.com'
social_icons:
  - name: Twitter
    icon: fa-twitter
    url: https://twitter.com/CarlHugoM
  - name: GitHub (ForEvolve)
    icon: fa-github
    url: https://github.com/ForEvolve
  - name: My GitHub Account
    icon: fa-github
    url: https://github.com/Carl-Hugo
  - name: LinkedIn
    icon: fa-linkedin
    url: https://www.linkedin.com/in/carl-hugo-marcotte
  - name: Twitch
    icon: fa-twitch
    url: https://www.twitch.tv/carlhugom
    hide: true
  - name: YouTube
    icon: fa-youtube
    url: https://www.youtube.com/channel/UCbRroQU-PWfTthu41qOf3OQ
    hide: true
  - name: Medium
    icon: fa-medium
    url: https://carlhugom.medium.com/
  - name: Dev.to
    icon: icomoon icon-dev-dot-to
    url: https://dev.to/carlhugom
  - name: RSS Feed
    icon: fa-rss
    url: /feed.xml
  - name: Email
    icon: fa-envelope
    url: mailto:blog@forevolve.com
follow-me-label: Follow me
default_lang: en

# Discus comments
comments: true
disqus_shortname: forevolve
kramdown:
  entity_output: numeric

# Google Analytics
google_tracking_id: UA-81489213-2

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ['less', 'node_modules', 'Gruntfile.js', 'package.json', 'README.md']

plugins: [jekyll-feed, jekyll-paginate, jekyll-redirect-from, jemoji]

excerpt_separator: <!--more-->

defaults:
  - scope:
      path: ''
      type: 'posts'
    values:
      layout: 'post'
      author: 'Carl-Hugo Marcotte'
  - scope:
      path: ''
      type: 'pages'
    values:
      layout: 'page'
